import launch
import launch_ros
from ament_index_python.packages import get_package_share_path
from launch_ros.parameter_descriptions import ParameterValue


def generate_launch_description():
    package_name = 'ustrov_remote_control'
    package_path = get_package_share_path(package_name)
    default_gains_file = package_path / 'config/joystick_gains_default.yaml'

    vehicle_name = launch.substitutions.LaunchConfiguration('vehicle_name')
    use_sim_time = launch.substitutions.LaunchConfiguration('use_sim_time')
    gains_file = launch.substitutions.LaunchConfiguration('joystick_gains_file')
    publish_rate = launch.substitutions.LaunchConfiguration('publish_rate')
    key_timeout = launch.substitutions.LaunchConfiguration('key_timeout')
    axis_value = launch.substitutions.LaunchConfiguration('axis_value')

    launch_args = [
        launch.actions.DeclareLaunchArgument(
            'vehicle_name',
            default_value='',
            description='Optional ROS namespace for this vehicle.',
        ),
        launch.actions.DeclareLaunchArgument(
            'use_sim_time',
            default_value='false',
            description='Use simulation clock when true.',
        ),
        launch.actions.DeclareLaunchArgument(
            'joystick_gains_file',
            default_value=str(default_gains_file),
            description='Gain file used by the existing joystick mapper.',
        ),
        launch.actions.DeclareLaunchArgument(
            'publish_rate',
            default_value='20.0',
            description='Virtual Joy publication rate in Hz.',
        ),
        launch.actions.DeclareLaunchArgument(
            'key_timeout',
            default_value='0.6',
            description='Seconds before a released key returns to zero.',
        ),
        launch.actions.DeclareLaunchArgument(
            'axis_value',
            default_value='1.0',
            description='Absolute virtual joystick value generated by a key.',
        ),
    ]

    keyboard_node = launch_ros.actions.Node(
        package=package_name,
        executable='keyboard_input_node',
        name='keyboard',
        namespace='',
        parameters=[{
            'use_sim_time': ParameterValue(use_sim_time, value_type=bool),
            'publish_rate': ParameterValue(publish_rate, value_type=float),
            'key_timeout': ParameterValue(key_timeout, value_type=float),
            'axis_value': ParameterValue(axis_value, value_type=float),
        }],
        output='screen',
        emulate_tty=True,
    )

    mapper_container = launch_ros.actions.ComposableNodeContainer(
        name='keyboard_mapper_container',
        namespace='',
        package='rclcpp_components',
        executable='component_container',
        composable_node_descriptions=[
            launch_ros.descriptions.ComposableNode(
                package=package_name,
                plugin='ustrov_remote_control::joystick::JoyStick',
                name='joystick_mapper',
                parameters=[
                    gains_file,
                    {
                        'use_sim_time': use_sim_time,
                        'mapping.use_4dof': True,
                    },
                ],
                extra_arguments=[{'use_intra_process_comms': True}],
            ),
        ],
        output='screen',
    )

    nodes_group = launch.actions.GroupAction([
        launch_ros.actions.PushRosNamespace(vehicle_name),
        keyboard_node,
        mapper_container,
    ])

    return launch.LaunchDescription(launch_args + [nodes_group])
